[context.production]
environment = { NETLIFY_EXPERIMENTAL_BUILD_RUST_SOURCE = "true" }

[functions]
directory = "./netlify/functions"

[[redirects]]
from = "/api/playground"
to = "/.netlify/functions/playground"
status = 200




