[context.production]
environment = { NETLIFY_EXPERIMENTAL_BUILD_RUST_SOURCE = "true" }

[functions]
directory = "./netlify/functions"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/hello/:splat"
status = 200




