[context.production]
environment = { NETLIFY_EXPERIMENTAL_BUILD_RUST_SOURCE = "true" }

[functions]
directory = "./netlify/functions"

[[redirects]]
from = "*"
to = "/.netlify/functions/hello-world/:splat"
status = 200

[build]
  command = "cargo build --target x86_64-unknown-linux-musl --release && cp target/x86_64-unknown-linux-musl/release/* functions/"
  functions = "functions"
  publish = "public"
