[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambda_http = "0.9.2"
serde_json = "1.0"
serde = "1.0.196"
tokio = { version = "1", features = ["full"] }